# Traffic PatchTST Configuration YAML

model_type: "PatchTST"
model: "PatchTST"
data: "custom"
root_path: "D:\\Coursework\\MTS\\dataset" 
data_path: "traffic.csv"
features: "M"
target: "OT"
freq: "h"
checkpoints: "./checkpoints/"
seq_len: 512
label_len: 48
pred_len: 96
fc_dropout: 0.2
head_dropout: 0.0
patch_len: 16
stride: 8
padding_patch: "end"
revin: 1
affine: 0
subtract_last: 0
decomposition: 0 
kernel_size: 25
individual: 0
embed_type: 0
enc_in: 862
dec_in: 862
c_out: 7
d_model: 128
predictor_d_model: 128
n_heads: 16
e_layers: 3
d_layers: 1
d_ff: 256
moving_avg: 25
factor: 1
distil: True
dropout: 0.2
embed: "timeF"
activation: "gelu"
output_attention: False
do_predict: False
num_workers: 2
itr: 1
# NUM EPOCHS
pretrain_epochs: 1
finetune_epochs: 1
batch_size: 24
patience: 50 
learning_rate: 0.0001
des: "Exp"
loss: "mse"
lradj: "type3"
pct_start: 0.3
use_amp: False
use_gpu: True
gpu: 0
use_multi_gpu: False
devices: '0,1,2,3'
test_flop: False
profile: False
scheduler: True
use_norm: True
# JEPA
enc_mask_scale: [0.85, 1]
pred_mask_scale: [0.15, 0.2]
use_embed: True
nenc: 1
npred: 3
allow_overlap: False
min_keep: 5
embedding_model: True
ema: [0.996, 1.0]
train_scale: 1.0